string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RUN_ID)
set(DEST "${OUTPUT_ROOT}/probe-simulation-${RUN_ID}")
execute_process(COMMAND "${PROBE}" --simulate --output "${DEST}" RESULT_VARIABLE RESULT OUTPUT_VARIABLE OUT ERROR_VARIABLE ERR)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Recorder simulation failed: ${RESULT} ${OUT} ${ERR}")
endif()
file(READ "${DEST}/report.json" REPORT)
string(JSON SIM GET "${REPORT}" simulation)
string(JSON SAMPLES GET "${REPORT}" samples)
string(JSON VALID GET "${REPORT}" formal_valid_samples)
string(JSON PAIRED GET "${REPORT}" paired_samples)
if(NOT SIM OR NOT SAMPLES STREQUAL "25" OR NOT VALID STREQUAL "20" OR NOT PAIRED STREQUAL "23")
    message(FATAL_ERROR "Unexpected simulation statistics: ${REPORT}")
endif()
file(SIZE "${DEST}/requests.jsonl" REQUEST_BYTES)
if(NOT REQUEST_BYTES EQUAL 0 OR EXISTS "${DEST}/INCOMPLETE")
    message(FATAL_ERROR "Simulation performed requests or did not finish")
endif()
file(STRINGS "${DEST}/SHA256SUMS.txt" SUMS)
foreach(LINE IN LISTS SUMS)
    string(SUBSTRING "${LINE}" 0 64 EXPECTED)
    string(SUBSTRING "${LINE}" 66 -1 NAME)
    file(SHA256 "${DEST}/${NAME}" ACTUAL)
    if(NOT ACTUAL STREQUAL EXPECTED)
        message(FATAL_ERROR "Output checksum mismatch: ${NAME}")
    endif()
endforeach()
execute_process(COMMAND "${PROBE}" --simulate --output "${DEST}" RESULT_VARIABLE REPEAT)
if(NOT REPEAT EQUAL 2)
    message(FATAL_ERROR "Must refuse to overwrite previous evidence")
endif()
execute_process(COMMAND "${PROBE}" --output "${DEST}-invalid" RESULT_VARIABLE INVALID)
if(NOT INVALID EQUAL 2 OR EXISTS "${DEST}-invalid")
    message(FATAL_ERROR "Missing explicit mode must fail before any capture")
endif()
